name: "✨ 新特性请求"
description: 为项目提出一个新想法或建议
title: '[新需求]: '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        **感谢您的新特性建议！**

        请花点时间填写以下表单，以便我们更好地理解您的需求。
        在提交之前，请确保：
        
        - 搜索现有的issues和讨论，确保这个特性尚未被提出
        - 确认这是一个新特性而不是bug修复
  - type: textarea
    id: problem-description
    attributes:
      label: 问题描述
      description: 您想解决什么问题？请简明扼要地描述您遇到的问题或痛点。
      placeholder: 我在使用产品时遇到的问题是...
    validations:
      required: true
  - type: textarea
    id: solution-description
    attributes:
      label: 解决方案描述
      description: 您建议如何解决这个问题？请描述您期望的功能或改进。
      placeholder: 我希望产品能够...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 您考虑过哪些替代解决方案或功能？
      placeholder: 我也考虑过通过...来解决这个问题
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: 其他上下文
      description: 您还有什么其他信息、截图或示例可以帮助我们更好地理解这个特性请求？
      placeholder: 其他相关信息...
    validations:
      required: false
  - type: dropdown
    id: importance
    attributes:
      label: 重要程度
      description: 您认为这个特性对您使用产品的重要程度如何？
      options:
        - 必需（无法没有它）
        - 重要（显著改善体验）
        - 一般（有帮助但不关键）
        - 微小（锦上添花）
    validations:
      required: false